### ISSUE TITLE
Reading pin 

### ISSUE THREAD

**Issue by doncebiti** [utilitydelta/dotnet-gpio#1]
Hi there,
i wery like Your package. but I found one problem.
If i set my pin value to high and i trying to read it it always set pin direction to input 
and always return false, but [documentation](https://www.kernel.org/doc/Documentation/gpio/sysfs.txt) says that you can read value does not matter set to input or output.

**Comment by utilitydelta** [comment]
Hi doncebiti,

You're right, I do set it back to input. My goal was to make it super easy to use, I was assuming that if you are reading the value, obviously it's pin input. To fix your scenario though, I've updated the package to 4.3.0 with a fix. PinValue now won't set the direction to In if it is already set to out. You should be able to read the value without the direction changing now ;)

Tyson
