### ISSUE TITLE
Gpio_ValueChanged implemented?

### ISSUE THREAD

**Issue by SimonR-Nano** [utilitydelta/dotnet-gpio#4]
Hello,

I'm looking a way to use [GPIO ValueChanged](https://docs.microsoft.com/en-us/uwp/api/windows.devices.gpio.gpiopin.valuechanged) in Net standard library.

Your library can do that?

Thank you for your job.

**Comment by utilitydelta** [comment]
Someone tried to do this with a FileSystemWatcher previously but it didn't work. 
https://github.com/utilitydelta-io/dotnet-gpio/pull/2
So at the moment, this library doesn't have any listening features.
If you have some suggestions on how to implement this properly, I'd be happy to take a look.
