### ISSUE TITLE
OS: Android 11 , Lib 4.3.0, Project: Maui App

### ISSUE THREAD

**Issue by mvasanthk** [utilitydelta/dotnet-gpio#5]
UtilityDelta.Gpio 4.3.0

Loaded assembly: /data/data/com.companyname.fctmv1/files/.__override__/System.Xml.XmlSerializer.dll [External]
Loaded assembly: /data/data/com.companyname.fctmv1/files/.__override__/UtilityDelta.Gpio.dll [External]
**System.UnauthorizedAccessException:** 'Access to the path '/sys/class/gpio/export' is denied.'

**Comment by utilitydelta** [comment]
Hey mate, try running your program with sudo? Or try this? https://stackoverflow.com/questions/30938991/access-gpio-sys-class-gpio-as-non-root
